version: '3'
services:
  db:
    container_name: testpsql
    image: postgres:11-alpine
    ports:
      - "7777:5432"
    command: [ "postgres", "-c", "log_statement=all", "-c", "log_destination=stderr" ]
    environment:
      POSTGRES_DB: "test-project"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"